[tool.commitizen]
name = "cz_customize"


[tool.commitizen.customize]
# message_template = "{{change_type}}:{% if show_message %} {{message}}{% endif %}"
message_template = """{{change_type}}: {{message}}
{% if commit_body != "" %} {{\n commit_body \n}}{% endif %}
{% if affected_issue != "" %} {{\n affected_issue \n}}{% endif %}
{% if reviewer != "" %} {{\n reviewer}}{% endif %}
"""
example = "feature: this feature enable customize through config file"
schema = "<type>: <body>"
schema_pattern = "(feature|bug fix):(\\s.*)"
bump_pattern = "^(break|new|fix|hotfix)"
bump_map = {break = "MAJOR", new = "MINOR", fix = "PATCH", hotfix = "PATCH"}
change_type_order = ["BREAKING CHANGE", "feat", "fix", "refactor", "perf"]
info_path = "cz_customize_info.txt"
info = """
This is customized info
"""

[[tool.commitizen.customize.questions]]
type = "list"
name = "change_type"
choices = [{ value = "added", name = "added: Add a new feature" }, { value = "fixed", name = "fixed: Fix a bug" },{ value = "merged", name = "merged: Resolves an issue and merge it to prod" }, { value = "refactored", name = "refactored: Does not add a feature or fix a bug" }, { value = "deprecated", name = "deprecated: Breaks compatibility with an earlier version" }]
# choices = ["feature", "fix"]  # short version
message = "Select the type of change you are committing"

[[tool.commitizen.customize.questions]]
type = "input"
name = "message"
message = "Enter a clear and descriptive commit message:"

[[tool.commitizen.customize.questions]]
type = "input"
name = "commit_body"
message = "Enter a detailed commit body (optional):"

[[tool.commitizen.customize.questions]]
type = "input"
name = "affected_issue"
message = "Enter the issue and how it's affected (ex: close #123) (optional):"

[[tool.commitizen.customize.questions]]
type = "input"
name = "reviewer"
message = "Enter the reviewer username (optional):"